import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Providers } from './providers'
import SideNav from '@/components/Navigation/SideNav'
import TopNav from '@/components/Navigation/TopNav'
import { Box } from '@chakra-ui/react'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Budget',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <SideNav />
          <div>
            <TopNav />
            <main className={inter.className}>
              <Box m={10}>
                {children}
              </Box>
            </main>
          </div>
        </Providers>
      </body>
    </html>
  )
}
