import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Providers } from './providers'
import SideNav from '@/components/SideNav/SideNav'
import TopNav from '@/components/TopNav/TopNav'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Budget',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div>
      <Providers>
        <SideNav />
        <div>
          <TopNav />
          <body className={inter.className}>
            {children}
          </body>
        </div>
      </Providers>
    </div>
  )
}
